package View.Home;

import DAOs.SpecificDAO;
import Model.Questoes;
import SqlCommands.Sql;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author augustosimionato
 */
public final class LessonView extends javax.swing.JFrame {

    private int[] idQuestoes;
    private ArrayList<Questoes> questoes = null;
    private static String sql;

    public LessonView(String sqls) {
        initComponents();
        difficult(sqls);
        try {
            SpecificDAO.CriaConexao();
            idQuestoes = carregaVetor();
            SpecificDAO.loadIdQuestion(sql, idQuestoes);
            questoes = SpecificDAO.loadQuestion();
            carregaQuestoes();
        } catch (SQLException erro) {
            System.out.println("Erro ao inicializar LessonView" + erro);
        }
    }

    public void difficult(String sql) {
        this.sql = sql;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldPergunta1 = new javax.swing.JLabel();
        textFieldResposta1 = new javax.swing.JTextField();
        textFieldPergunta2 = new javax.swing.JLabel();
        textFieldResposta2 = new javax.swing.JTextField();
        textFieldPergunta3 = new javax.swing.JLabel();
        textFieldResposta3 = new javax.swing.JTextField();
        buttonVerificar = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        buttonResposta = new javax.swing.JButton();
        textFieldCorreta1 = new javax.swing.JLabel();
        textFieldCorreta3 = new javax.swing.JLabel();
        textFieldCorreta2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        goBackMenu = new javax.swing.JMenu();
        contentMenu = new javax.swing.JMenu();
        easyMenuItem = new javax.swing.JMenuItem();
        mediumMenuItem = new javax.swing.JMenuItem();
        hardMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Comece sua jornada");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 553));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Traduza as frases a seguir");

        textFieldPergunta1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        textFieldPergunta1.setText("Frase 1 aqui");

        textFieldResposta1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resposta"));

        textFieldPergunta2.setText("Frase 2 aqui");

        textFieldResposta2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resposta"));

        textFieldPergunta3.setText("Frase 3 aqui");

        textFieldResposta3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resposta"));

        buttonVerificar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        buttonVerificar.setText("Verificar");
        buttonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerificarActionPerformed(evt);
            }
        });

        finishButton.setText("Finalizar");
        finishButton.setEnabled(false);
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        buttonResposta.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        buttonResposta.setText("Mostrar respostas");
        buttonResposta.setEnabled(false);
        buttonResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRespostaActionPerformed(evt);
            }
        });

        textFieldCorreta1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        textFieldCorreta3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        textFieldCorreta2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(textFieldPergunta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldResposta3)
                    .addComponent(textFieldResposta2)
                    .addComponent(textFieldResposta1)
                    .addComponent(textFieldPergunta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldPergunta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldCorreta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldCorreta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldCorreta2, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(buttonVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonResposta)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldPergunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textFieldResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCorreta1)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldPergunta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldResposta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCorreta2)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldPergunta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldCorreta3)
                        .addContainerGap(137, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(180, 180, 180)
                        .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        goBackMenu.setText("Voltar");
        goBackMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(goBackMenu);

        contentMenu.setText("Conteúdo");

        easyMenuItem.setText("Comece sua jornada");
        easyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyMenuItemActionPerformed(evt);
            }
        });
        contentMenu.add(easyMenuItem);

        mediumMenuItem.setText("Continue sua jornada");
        mediumMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumMenuItemActionPerformed(evt);
            }
        });
        contentMenu.add(mediumMenuItem);

        hardMenuItem.setText("Finalizando a jornada");
        hardMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardMenuItemActionPerformed(evt);
            }
        });
        contentMenu.add(hardMenuItem);

        jMenuBar1.add(contentMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1040, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackMenuMouseClicked
        this.dispose();
        new View.Home.HomeView().setVisible(true);
    }//GEN-LAST:event_goBackMenuMouseClicked

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        this.dispose();
        new CongratulationsView().setVisible(true);
    }//GEN-LAST:event_finishButtonActionPerformed

    private void buttonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerificarActionPerformed
        boolean allFieldsFilled = !textFieldResposta1.getText().isEmpty()
                && !textFieldResposta2.getText().isEmpty()
                && !textFieldResposta3.getText().isEmpty();

        if (!allFieldsFilled) {
            JOptionPane.showMessageDialog(this,
                    "Complete todos os exercícios antes de continuar",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            boolean answer1Correct = textFieldResposta1.getText().equals(questoes.get(0).getResposta());
            boolean answer2Correct = textFieldResposta2.getText().equals(questoes.get(1).getResposta());
            boolean answer3Correct = textFieldResposta3.getText().equals(questoes.get(2).getResposta());

            if (answer1Correct && answer2Correct && answer3Correct) {
                finishButton.setEnabled(true);
            } else {
                StringBuilder errorMessage = new StringBuilder("As seguintes questões estão incorretas:\n");

                if (!answer1Correct) {
                    errorMessage.append("Questão 1\n");
                }
                if (!answer2Correct) {
                    errorMessage.append("Questão 2\n");
                }
                if (!answer3Correct) {
                    errorMessage.append("Questão 3\n");
                }

                JOptionPane.showMessageDialog(this,
                        errorMessage.toString(),
                        "Eita!",
                        JOptionPane.WARNING_MESSAGE);
                buttonResposta.setEnabled(true);
            }
        }
    }//GEN-LAST:event_buttonVerificarActionPerformed

    private void buttonRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRespostaActionPerformed
        textFieldCorreta1.setText(questoes.get(0).getResposta());
        textFieldCorreta2.setText(questoes.get(1).getResposta());
        textFieldCorreta3.setText(questoes.get(2).getResposta());
    }//GEN-LAST:event_buttonRespostaActionPerformed

    private void easyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyMenuItemActionPerformed
        new View.Content.EasyContentView().setVisible(true);
    }//GEN-LAST:event_easyMenuItemActionPerformed

    private void mediumMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumMenuItemActionPerformed
        new View.Content.MediumContentView().setVisible(true);
    }//GEN-LAST:event_mediumMenuItemActionPerformed

    private void hardMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardMenuItemActionPerformed
        new View.Content.HardContentView().setVisible(true);
    }//GEN-LAST:event_hardMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonView(Sql.selectQuestionE).setVisible(true);
            }
        });
    }

    public int[] carregaVetor() {
        int[] vetor = new int[3];
        Set<Integer> numerosUsados = new HashSet<>();
        Random random = new Random();
        int i = 0;
        while (i < vetor.length) {
            int numeroAleatorio = random.nextInt(8) + 1;
            if (!numerosUsados.contains(numeroAleatorio)) {
                vetor[i] = numeroAleatorio;
                numerosUsados.add(numeroAleatorio);
                i++;
            }
        }
        return vetor;
    }

    public void carregaQuestoes() {
        textFieldPergunta1.setText(questoes.get(0).getPergunta());
        textFieldPergunta2.setText(questoes.get(1).getPergunta());
        textFieldPergunta3.setText(questoes.get(2).getPergunta());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonResposta;
    private javax.swing.JButton buttonVerificar;
    private javax.swing.JMenu contentMenu;
    private javax.swing.JMenuItem easyMenuItem;
    private javax.swing.JButton finishButton;
    private javax.swing.JMenu goBackMenu;
    private javax.swing.JMenuItem hardMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mediumMenuItem;
    private javax.swing.JLabel textFieldCorreta1;
    private javax.swing.JLabel textFieldCorreta2;
    private javax.swing.JLabel textFieldCorreta3;
    private javax.swing.JLabel textFieldPergunta1;
    private javax.swing.JLabel textFieldPergunta2;
    private javax.swing.JLabel textFieldPergunta3;
    private javax.swing.JTextField textFieldResposta1;
    private javax.swing.JTextField textFieldResposta2;
    private javax.swing.JTextField textFieldResposta3;
    // End of variables declaration//GEN-END:variables
}
