package View.Home;

import DAOs.SpecificDAO;
import View.LoginView;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author augustosimionato
 */
public class SettingsView extends javax.swing.JFrame {

    public SettingsView() {
        try {
            initComponents();
            SpecificDAO.loadSettings(LoginView.getIdLogin());
            UserNameTextField.setText(SpecificDAO.getUsuario());
            EmailTextField.setText(SpecificDAO.getEmail());
            jLabelDate.setText(SpecificDAO.getDate().toString());
        } catch (SQLException erro) {
            System.out.println("Erro ao iniciar Settings" + erro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProfilePhotoLabel = new javax.swing.JLabel();
        UserNameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        jLabelDate = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        GoBack = new javax.swing.JMenu();
        Options = new javax.swing.JMenu();
        EditDataMenuItem = new javax.swing.JMenuItem();
        DeleteAccountMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 576));

        ProfilePhotoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfilePhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/profile.png"))); // NOI18N

        UserNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserNameTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome de usuário"));
        UserNameTextField.setEnabled(false);

        EmailTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        EmailTextField.setEnabled(false);

        jLabelDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta criada em"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ProfilePhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(397, 397, 397))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(ProfilePhotoLabel)
                .addGap(18, 18, 18)
                .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        GoBack.setText("Voltar");
        GoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackMouseClicked(evt);
            }
        });
        jMenuBar1.add(GoBack);

        Options.setText("Opções");

        EditDataMenuItem.setText("Mudar Senha");
        EditDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDataMenuItemActionPerformed(evt);
            }
        });
        Options.add(EditDataMenuItem);

        DeleteAccountMenuItem.setText("Apagar conta");
        DeleteAccountMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountMenuItemActionPerformed(evt);
            }
        });
        Options.add(DeleteAccountMenuItem);

        jMenuBar1.add(Options);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1038, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackMouseClicked
        this.dispose();
        new HomeView().setVisible(true);
    }//GEN-LAST:event_GoBackMouseClicked

    private void DeleteAccountMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountMenuItemActionPerformed
        int response = JOptionPane.showConfirmDialog(this,
                "Você tem certeza que deseja apagar sua conta?",
                "Apagar conta",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            if (SpecificDAO.excluir(LoginView.getIdLogin())) {
                JOptionPane.showMessageDialog(this,
                        "Conta apagada com sucesso!",
                        "Apagar conta",
                        JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                LoginView.getLogin().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this,
                        "Erro ao deletar Usuario!",
                        "Apagar conta",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteAccountMenuItemActionPerformed

    private void EditDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDataMenuItemActionPerformed
        new MudarSenha().setVisible(true);
    }//GEN-LAST:event_EditDataMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DeleteAccountMenuItem;
    private javax.swing.JMenuItem EditDataMenuItem;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JMenu GoBack;
    private javax.swing.JMenu Options;
    private javax.swing.JLabel ProfilePhotoLabel;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
