package View;

/**
 * @author augustosimionato
 */
public class LoginView extends javax.swing.JFrame {

    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoHome = new javax.swing.JButton();
        GoNewAccount = new javax.swing.JButton();
        UserNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        GoHome.setText("Entrar");
        GoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoHomeActionPerformed(evt);
            }
        });
        getContentPane().add(GoHome);
        GoHome.setBounds(290, 360, 190, 40);

        GoNewAccount.setText("Criar nova conta");
        GoNewAccount.setBorder(null);
        GoNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoNewAccountActionPerformed(evt);
            }
        });
        getContentPane().add(GoNewAccount);
        GoNewAccount.setBounds(330, 410, 110, 30);

        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameField);
        UserNameField.setBounds(270, 210, 230, 40);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Senha");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 260, 60, 18);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 190, 60, 18);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/title.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 50, 350, 70);
        getContentPane().add(PasswordField);
        PasswordField.setBounds(270, 290, 230, 40);

        setSize(new java.awt.Dimension(766, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoHomeActionPerformed
        new View.Home.HomeView().setVisible(true);
    }//GEN-LAST:event_GoHomeActionPerformed

    private void GoNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoNewAccountActionPerformed
        new NewAccountView().setVisible(true);
    }//GEN-LAST:event_GoNewAccountActionPerformed

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFieldActionPerformed
        
    }//GEN-LAST:event_UserNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoHome;
    private javax.swing.JButton GoNewAccount;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
